### ISSUE TITLE
CIS 1.11.0 crashes in rancher k3s behind proxy server 

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#1059]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>

CIS 1.11.0 added getting AS3 schema from Internet for as3 validation, cluster running behind company proxy may fail to get the remote AS3 schema and thus fail

<pre>
const as3SchemaLatestUrl = "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json"

	// AS3 schema validation using latest AS3 version
	fetchAS3Schema(appMgr)
func fetchAS3Schema(appMgr *appmanager.Manager) {

	res, resErr := http.Get(as3SchemaLatestUrl)
	if resErr != nil {
		log.Debugf("error while fetching latest as3 schema : %v", resErr)
	}

	if res.StatusCode == http.StatusOK {

</pre>

#### Kubernetes Version

Rancher k3s version 0.5.0

#### Controller Version
CIS 1.11.0

#### BIG-IP Version
13.1.1

#### Diagnostic Information

root@rancher-k3s home]# kubectl logs cc-cluster-5897dbcd58-bx4xl -n kube-system
2019/10/24 20:38:18 [INFO] Starting: Version: v1.11.0, BuildInfo: n1829-595947561
2019/10/24 20:38:18 [INFO] ConfigWriter started: 0xc0002d9920
2019/10/24 20:38:18 [INFO] Started config driver sub-process at pid: 12
2019/10/24 20:38:18 [INFO] ConfigWriter stopped: 0xc0002d9920
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11b8f5b]

goroutine 1 [running]:
main.fetchAS3Schema(0xc0002b7600)
	/build/src/github.com/F5Networks/k8s-bigip-ctlr/cmd/k8s-bigip-ctlr/main.go:788 +0x10b
main.main()
	/build/src/github.com/F5Networks/k8s-bigip-ctlr/cmd/k8s-bigip-ctlr/main.go:743 +0xcde

**Comment by vincentmli** [comment]
this is duplicate of https://github.com/F5Networks/k8s-bigip-ctlr/issues/1040, closing
