### ISSUE TITLE
Controller stops creating Virtual servers unless restarted

### ISSUE THREAD

**Issue by rveve** [F5Networks/k8s-bigip-ctlr#1144]
Hi,

I am running latest controller 1.12.0, almost every few hours, I am getting this error below, and when it happens the controller literally stops sending requests to the BigIP endpoint. No traffic seen
from tcpdump. If I restart the controller pod, everything works perfectly for the next few
hours.

```
2020/01/04 08:16:22 [ERROR] [2020-01-04 08:16:22,589 __main__ ERROR] Unexpected error
2020/01/04 08:16:22 [INFO] Traceback (most recent call last):
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 323, in _do_reset
2020/01/04 08:16:22 [INFO]     incomplete = self._update_cccl(config)
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 397, in _update_cccl
2020/01/04 08:16:22 [INFO]     incomplete += mgr._apply_ltm_config(cfg_ltm)
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 117, in _apply_ltm_config
2020/01/04 08:16:22 [INFO]     return self._cccl.apply_ltm_config(config)
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-cccl/f5_cccl/api.py", line 92, in apply_ltm_config
2020/01/04 08:16:22 [INFO]     self._user_agent)
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 670, in apply_ltm_config
2020/01/04 08:16:22 [INFO]     desired_config, default_route_domain)
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 458, in deploy_ltm
2020/01/04 08:16:22 [INFO]     self._post_deploy(desired_config, default_route_domain)
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 330, in _post_deploy
2020/01/04 08:16:22 [INFO]     self._bigip.refresh_ltm()
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 136, in refresh_ltm
2020/01/04 08:16:22 [INFO]     self._refresh_ltm()
2020/01/04 08:16:22 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 278, in _refresh_ltm
2020/01/04 08:16:22 [INFO]     requests_params={"params": query})
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 781, in get_collection
2020/01/04 08:16:22 [INFO]     self.refresh(**kwargs)
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 651, in refresh
2020/01/04 08:16:22 [INFO]     self._refresh(**kwargs)
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 634, in _refresh
2020/01/04 08:16:22 [INFO]     response = refresh_session.get(uri, **requests_params)
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/session.py", line 257, in wrapper
2020/01/04 08:16:22 [INFO]     response = method(self, REST_uri, **kwargs)
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/session.py", line 462, in get
2020/01/04 08:16:22 [INFO]     return self.session.get(uri, **kwargs)
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
2020/01/04 08:16:22 [INFO]     return self.request('GET', url, **kwargs)
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
2020/01/04 08:16:22 [INFO]     resp = self.send(prep, **send_kwargs)
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 677, in send
2020/01/04 08:16:22 [INFO]     r.content
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 828, in content
2020/01/04 08:16:22 [INFO]     self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
2020/01/04 08:16:22 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 753, in generate
2020/01/04 08:16:22 [INFO]     raise ChunkedEncodingError(e)
2020/01/04 08:16:22 [INFO] ChunkedEncodingError: ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))
2020/01/04 08:16:22 [ERROR] [2020-01-04 08:16:22,591 __main__ ERROR] Error applying config, will try again in 1 seconds
```

**Comment by veeramalla-f5** [comment]
Hi , 

 Can you provide more information on your configuration files? We will appreciate if you can share your cis deployment file and k8s resource files.

Regards,
Abhishek Veeramalla.

**Comment by mdditt2000** [comment]
@rveve can you please update the controller to 1.13. Lots of stability fixes

**Comment by mdditt2000** [comment]
Closing this issue. If you continue to experience this issue please open a new issue. CIS 2.0 releasing this week.
