### ISSUE TITLE
Log contains plaintext credentials

### ISSUE THREAD

**Issue by anfernee** [F5Networks/k8s-bigip-ctlr#1462]
#### Setup Details
 CIS Version : 1.14      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: CCCL       
 Orchestration: K8S
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
  
The controller logs the body of a login request on error which contains plain-text credentials:

```
2019/06/03 17:39:57 [ERROR] [2019-06-03 17:39:57,697 __main__ ERROR] Unexpected error
2019/06/03 17:39:57 [INFO] Traceback (most recent call last):
2019/06/03 17:39:57 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 323, in _do_reset
2019/06/03 17:39:57 [INFO]     incomplete = self._update_cccl(config)
2019/06/03 17:39:57 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 397, in _update_cccl
2019/06/03 17:39:57 [INFO]     incomplete += mgr._apply_ltm_config(cfg_ltm)
2019/06/03 17:39:57 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 117, in _apply_ltm_config
2019/06/03 17:39:57 [INFO]     return self._cccl.apply_ltm_config(config)
2019/06/03 17:39:57 [INFO]   File "/app/src/f5-cccl/f5_cccl/api.py", line 92, in apply_ltm_config
2019/06/03 17:39:57 [INFO]     self._user_agent)
2019/06/03 17:39:57 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 662, in apply_ltm_config
2019/06/03 17:39:57 [INFO]     default_route_domain = self._bigip.get_default_route_domain()
2019/06/03 17:39:57 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 433, in get_default_route_domain
2019/06/03 17:39:57 [INFO]     name=self._partition)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 1054, in load
2019/06/03 17:39:57 [INFO]     return self._load(**kwargs)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 1033, in _load
2019/06/03 17:39:57 [INFO]     response = refresh_session.get(base_uri, **kwargs)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/session.py", line 257, in wrapper
2019/06/03 17:39:57 [INFO]     response = method(self, REST_uri, **kwargs)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/session.py", line 462, in get
2019/06/03 17:39:57 [INFO]     return self.session.get(uri, **kwargs)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
2019/06/03 17:39:57 [INFO]     return self.request('GET', url, **kwargs)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 510, in request
2019/06/03 17:39:57 [INFO]     prep = self.prepare_request(req)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 453, in prepare_request
2019/06/03 17:39:57 [INFO]     hooks=merge_hooks(request.hooks, self.hooks),
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 317, in prepare
2019/06/03 17:39:57 [INFO]     self.prepare_auth(auth, url)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 548, in prepare_auth
2019/06/03 17:39:57 [INFO]     r = auth(self)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/authtoken.py", line 254, in __call__
2019/06/03 17:39:57 [INFO]     self.get_new_token(netloc)
2019/06/03 17:39:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/authtoken.py", line 160, in get_new_token
2019/06/03 17:39:57 [INFO]     response=response)
2019/06/03 17:39:57 [INFO] iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://100.115.254.195:443/mgmt/shared/authn/login
2019/06/03 17:39:57 [INFO] Text: u'{"code":400,"message":"remoteSender:100.115.250.117, method:POST ","originalRequestBody":"{\\"username\\": \\"REDACTED\\", \\"password\\": \\"REDACTED\\", \\"loginProviderName\\": \\"tmos\\"}","referer":"100.115.250.117","restOperationId":28457074,"kind":":resterrorresponse"}'
2019/06/03 17:39:57 [ERROR] [2019-06-03 17:39:57,698 __main__ ERROR] Error applying config, will try again in 128 seconds
```

#### Steps To Reproduce
1) Deploy CIS in Kubernetes
2) Provide some bad configuration
3) Check the log message

#### Expected Result 
The credential shouldn't appear in the log

#### Actual Result  
Log message contains the user credentials.

**Comment by cisbotctlr** [comment]
cisbot will assign the issue to one of the devs. 
 @devs, use /jira for internal tracking.

**Comment by mdditt2000** [comment]
@anfernee please can can you one a support ticket SR with F5 support. Please open using iControlUnexpectedHTTPError responding with "originalRequestBody":"{\\"username\\": \\"REDACTED\\", \\"password\\": \\"REDACTED\\".

Please send me the SR number once opened. CIS is the client and therefore should receive such a response from BIG-IP. 

I noticed you using CCCL. CIS is moving forward using agent AS3. Can we move to agent AS3?

**Comment by mdditt2000** [comment]
@anfernee did you open a support SR with F5 support?

**Comment by mdditt2000** [comment]
Plus @memes

**Comment by trinaths** [comment]
Tried this scenario with wrong credentials on 2.4.1 and BIGIP 15.1.2.1 Build 0.0.10 Point Release 1.

```
2021/07/09 08:26:56 [ERROR] [2021-07-09 08:26:56,828 __main__ ERROR] Encountered error: BIG-IP connection error: 401 Unexpected Error: F5 Authorization Required for uri: https://10.145.79.202:443/mgmt/shared/authn/login
2021/07/09 08:26:56 [INFO] Text: '{"code":401,"message":"Authentication failed.","originalRequestBody":"{\\"username\\":\\"admin\\",\\"loginProviderName\\":\\"tmos\\",\\"generation\\":0,\\"lastUpdateMicros\\":0}","referer":"10.144.138.84","restOperationId":43487692,"kind":":resterrorresponse"}'. Retrying for 2 seconds.
```
Log contains the plaintext credentials with username and not the password. However, CIS is a client and the issue needs to be fixed from iControlReST response messages. Please raise an SR to further resolve this issue.

Closing this issue.
