### ISSUE TITLE
cis through unexpected error

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#1634]
CIS 2.0.0 cis through unexpected error as below, but it can still works, push confimap via AS3

~~~
2021/01/15 07:28:52 [ERROR] [2021-01-15 07:28:52,821 __main__ ERROR] Unexpected error
2021/01/15 07:28:52 [ERROR] [2021-01-15 07:28:52,822 __main__ ERROR] Error applying config, will try again in 128 seconds
2021/01/15 07:28:52 [INFO] Traceback (most recent call last):
2021/01/15 07:28:52 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 325, in _do_reset
2021/01/15 07:28:52 [INFO]     incomplete = self._update_cccl(config)
2021/01/15 07:28:52 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 399, in _update_cccl
2021/01/15 07:28:52 [INFO]     incomplete += mgr._apply_ltm_config(cfg_ltm)
2021/01/15 07:28:52 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 117, in _apply_ltm_config
2021/01/15 07:28:52 [INFO]     return self._cccl.apply_ltm_config(config)
2021/01/15 07:28:52 [INFO]   File "/app/src/f5-cccl/f5_cccl/api.py", line 92, in apply_ltm_config
2021/01/15 07:28:52 [INFO]     self._user_agent)
2021/01/15 07:28:52 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 662, in apply_ltm_config
2021/01/15 07:28:52 [INFO]     default_route_domain = self._bigip.get_default_route_domain()
2021/01/15 07:28:52 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 433, in get_default_route_domain
2021/01/15 07:28:52 [INFO]     name=self._partition)
2021/01/15 07:28:52 [INFO]   File "/usr/local/lib/python3.6/site-packages/f5/bigip/resource.py", line 1054, in load
2021/01/15 07:28:52 [INFO]     return self._load(**kwargs)
2021/01/15 07:28:52 [INFO]   File "/usr/local/lib/python3.6/site-packages/f5/bigip/resource.py", line 1033, in _load
2021/01/15 07:28:52 [INFO]     response = refresh_session.get(base_uri, **kwargs)
2021/01/15 07:28:52 [INFO]   File "/usr/local/lib/python3.6/site-packages/icontrol/session.py", line 271, in wrapper
2021/01/15 07:28:52 [INFO]     raise iControlUnexpectedHTTPError(error_message, response=response)
2021/01/15 07:28:52 [INFO] icontrol.exceptions.iControlUnexpectedHTTPError: 404 Unexpected Error: Not Found for uri: https://192.168.200.208:443/mgmt/tm/auth/partition/k8s
2021/01/15 07:28:52 [INFO] Text: '{"code":404,"message":"01020036:3: The requested partition (k8s) was not found.","errorStack":[],"apiError":3}'
~~~

the CIS deployment looks

~~~
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr
  namespace: bigip-ctlr
  labels:
    app: k8s-bigip-ctlr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:2.0.0"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=https://10.1.10.240:443",
            "--insecure=true",
            "--bigip-partition=k8s",
            "--log-level=INFO",
            "--namespace=test01",
            "--pool-member-type=cluster"
            ]
~~~

**Comment by trinaths** [comment]
@kylinsoong  Can you verify this with v2.2.2 and share your findings.

**Comment by kylinsoong** [comment]
@trinaths Start from 2.1, this issue was gone.

**Comment by trinaths** [comment]
@kylinsoong - Thank you for the update. closing this issue.
