### ISSUE TITLE
Cannot Build 1.14 version

### ISSUE THREAD

**Issue by achontzo** [F5Networks/k8s-bigip-ctlr#1717]
#### Setup Details
 CIS Version : 1.14      
 Build: f5networks/k8s-bigip-ctlr:1.14-stable       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:       
 Pool Mode: Cluster/Nodeport      
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
Official Build procedure fails.  

#### Steps To Reproduce
1)git clone https://github.com/f5networks/k8s-bigip-ctlr.git
2)git checkout 1.14-stable
3)make prod

#### Expected Result 
A docker image

#### Actual Result  
N/A

#### Diagnostic Information
```buildoutcfg
Step 12/16 : RUN pip install --no-cache-dir --upgrade pip &&     pip install --no-cache-dir setuptools flake8 virtualenv && 	pip install --no-cache-dir -r /tmp/requirements.txt && 	pip install --no-cache-dir -r /tmp/requirements.docs.txt && 	go get github.com/wadey/gocovmerge && 	go get golang.org/x/tools/cmd/cover && 	go get github.com/mattn/goveralls && 	go get github.com/onsi/ginkgo/ginkgo && 	go get github.com/onsi/gomega && 	chmod 755 /entrypoint.sh
 ---> Running in 7b6c95f92afb
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (53.0.0)
Collecting flake8
  Downloading flake8-3.8.4-py2.py3-none-any.whl (72 kB)
Collecting virtualenv
  Downloading virtualenv-20.4.2-py2.py3-none-any.whl (7.2 MB)
Collecting importlib-metadata
  Downloading importlib_metadata-3.4.0-py3-none-any.whl (10 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting filelock<4,>=3.0.0
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting appdirs<2,>=1.4.3
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting six<2,>=1.9.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting importlib-resources>=1.0
  Downloading importlib_resources-5.1.0-py3-none-any.whl (24 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Collecting typing-extensions>=3.6.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Installing collected packages: zipp, typing-extensions, six, pyflakes, pycodestyle, mccabe, importlib-resources, importlib-metadata, filelock, distlib, appdirs, virtualenv, flake8
Successfully installed appdirs-1.4.4 distlib-0.3.1 filelock-3.0.12 flake8-3.8.4 importlib-metadata-3.4.0 importlib-resources-5.1.0 mccabe-0.6.1 pycodestyle-2.6.0 pyflakes-2.2.0 six-1.15.0 typing-extensions-3.7.4.3 virtualenv-20.4.2 zipp-3.4.0
Obtaining f5-ctlr-agent from git+https://github.com/f5devcentral/f5-ctlr-agent.git@29e8a032b89fad442c4c4f1d5b6465d3d6578f34#egg=f5-ctlr-agent (from -r /tmp/requirements.txt (line 1))
  Cloning https://github.com/f5devcentral/f5-ctlr-agent.git (to revision 29e8a032b89fad442c4c4f1d5b6465d3d6578f34) to ./src/f5-ctlr-agent
  Running command git clone -q https://github.com/f5devcentral/f5-ctlr-agent.git /go/src/f5-ctlr-agent
  Running command git rev-parse -q --verify 'sha^29e8a032b89fad442c4c4f1d5b6465d3d6578f34'
  Running command git fetch -q https://github.com/f5devcentral/f5-ctlr-agent.git 29e8a032b89fad442c4c4f1d5b6465d3d6578f34
  Running command git checkout -q 29e8a032b89fad442c4c4f1d5b6465d3d6578f34
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/go/src/f5-ctlr-agent/setup.py'"'"'; __file__='"'"'/go/src/f5-ctlr-agent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bdbsro68
         cwd: /go/src/f5-ctlr-agent/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/go/src/f5-ctlr-agent/setup.py", line 33, in <module>
        install_reqs.append(str(req.req))
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
WARNING: Discarding git+https://github.com/f5devcentral/f5-ctlr-agent.git@29e8a032b89fad442c4c4f1d5b6465d3d6578f34#egg=f5-ctlr-agent. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Obtaining f5-cccl from git+https://github.com/f5devcentral/f5-cccl.git@f2498ad9e72e430005f66e5f9747498ce057ead7#egg=f5-cccl (from -r /tmp/requirements.txt (line 2))
  Running command git clone -q https://github.com/f5devcentral/f5-cccl.git /go/src/f5-cccl
  Cloning https://github.com/f5devcentral/f5-cccl.git (to revision f2498ad9e72e430005f66e5f9747498ce057ead7) to ./src/f5-cccl
  Running command git rev-parse -q --verify 'sha^f2498ad9e72e430005f66e5f9747498ce057ead7'
  Running command git fetch -q https://github.com/f5devcentral/f5-cccl.git f2498ad9e72e430005f66e5f9747498ce057ead7
  Running command git checkout -q f2498ad9e72e430005f66e5f9747498ce057ead7
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/go/src/f5-cccl/setup.py'"'"'; __file__='"'"'/go/src/f5-cccl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iha6iibu
         cwd: /go/src/f5-cccl/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/go/src/f5-cccl/setup.py", line 28, in <module>
        session='setup')]
      File "/go/src/f5-cccl/setup.py", line 27, in <listcomp>
        install_requires = [str(x.req) for x in parse_reqs('./setup_requirements.txt',
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
WARNING: Discarding git+https://github.com/f5devcentral/f5-cccl.git@f2498ad9e72e430005f66e5f9747498ce057ead7#egg=f5-cccl. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement f5-ctlr-agent (unavailable)
ERROR: No matching distribution found for f5-ctlr-agent (unavailable)
Removing intermediate container 7b6c95f92afb
The command '/bin/sh -c pip install --no-cache-dir --upgrade pip &&     pip install --no-cache-dir setuptools flake8 virtualenv && 	pip install --no-cache-dir -r /tmp/requirements.txt && 	pip install --no-cache-dir -r /tmp/requirements.docs.txt && 	go get github.com/wadey/gocovmerge && 	go get golang.org/x/tools/cmd/cover && 	go get github.com/mattn/goveralls && 	go get github.com/onsi/ginkgo/ginkgo && 	go get github.com/onsi/gomega && 	chmod 755 /entrypoint.sh' returned a non-zero code: 1
Makefile:87: recipe for target 'prod-build' failed
make: *** [prod-build] Error 1

```  

#### Observations (if any)
It also happens on master.

**Comment by trinaths** [comment]
Created  CONTCNTR-2488 for internal tracking

**Comment by trinaths** [comment]
@achontzo Please apply the patch attached to 1.14 codebase and try `make prod` or `make prod-quick`. 
The attached changes worked will with the build image generation. Share your findings.

[1717.patch.txt](https://github.com/F5Networks/k8s-bigip-ctlr/files/6061687/1717.patch.txt)

**Comment by achontzo** [comment]
make prod worked like a charm. Thanks

**Comment by trinaths** [comment]
closing this issue thank you
