### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kylinsoong** [F5Networks/k8s-bigip-ctlr#2466]
#### Setup Details
 CIS Version : 2.1.1
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 15.1      
 AS3 Version: 3.25     
 Agent Mode: AS3     
 Orchestration: K8S   
 Orchestration Version:   1.18
 Pool Mode: Cluster

#### Description  
 
CIS crashed and restart many times with the following error each time

~~~
2022-06-23 E0623 11:22:53.863403       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
2022-06-23 goroutine 79 [running]:
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1454020, 0x25e9e40)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
2022-06-23 panic(0x1454020, 0x25e9e40)
2022-06-23      /usr/local/go/src/runtime/panic.go:522 +0x1b5
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).syncConfigMaps(0xc000444000, 0xc001c9da40, 0xc0010de5da, 0x6, 0x0, 0x0, 0xc0010de5b0, 0xf, 0x15e6ad5, 0x6, ...)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1038 +0x18d3
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).syncVirtualServer(0xc000444000, 0xc0010de5da, 0x6, 0x0, 0x0, 0xc0010de5b0, 0xf, 0x15e6ad5, 0x6, 0xc0002b8000, ...)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:985 +0x86f
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).processNextVirtualServer(0xc000444000, 0xc0000da100)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:888 +0x15b
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).virtualServerWorker(0xc000444000)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:834 +0x2b
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005a2090)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005a2090, 0x3b9aca00, 0x0, 0x1, 0xc0000bd200)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0005a2090, 0x3b9aca00, 0xc0000bd200)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
2022-06-23 created by github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).runImpl
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:778 +0x13d
2022-06-23 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-06-23      panic: runtime error: invalid memory address or nil pointer dereference
2022-06-23 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12b6da3]
2022-06-23
2022-06-23 goroutine 79 [running]:
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
2022-06-23 panic(0x1454020, 0x25e9e40)
2022-06-23      /usr/local/go/src/runtime/panic.go:522 +0x1b5
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).syncConfigMaps(0xc000444000, 0xc001c9da40, 0xc0010de5da, 0x6, 0x0, 0x0, 0xc0010de5b0, 0xf, 0x15e6ad5, 0x6, ...)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1038 +0x18d3
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).syncVirtualServer(0xc000444000, 0xc0010de5da, 0x6, 0x0, 0x0, 0xc0010de5b0, 0xf, 0x15e6ad5, 0x6, 0xc0002b8000, ...)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:985 +0x86f
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).processNextVirtualServer(0xc000444000, 0xc0000da100)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:888 +0x15b
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).virtualServerWorker(0xc000444000)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:834 +0x2b
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005a2090)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005a2090, 0x3b9aca00, 0x0, 0x1, 0xc0000bd200)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
2022-06-23 github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0005a2090, 0x3b9aca00, 0xc0000bd200)
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
2022-06-23 created by github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).runImpl
2022-06-23      /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:778 +0x13d
~~~

#### Steps To Reproduce

No Reproduction at the moments, the error come from production environment

**Comment by trinaths** [comment]
@kylinsoong  - Please update to 2.9 and share your findings.

**Comment by trinaths** [comment]
Not reproducible. Closing this github issue.
