### ISSUE TITLE
Invalid YAML crashes k8s-bigip-ctlr?

### ISSUE THREAD

**Issue by hickey** [F5Networks/k8s-bigip-ctlr#353]
In the process of working with the Container Connector, I just applied a new YAML definition and had the k8s-bigip-ctlr container exit out. Below is the log output that was generated when applying the updated YAML definition for an existing job was updated. 

````
2017/09/26 20:29:42 [INFO] Wrote 6 Virtual Server configs
2017/09/26 20:30:00 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:30:30 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:31:00 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:31:30 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:32:00 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:32:30 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:33:00 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:33:30 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:34:00 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:34:30 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:35:00 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:35:22 [INFO] Wrote 5 Virtual Server configs
2017/09/26 20:35:30 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:35:53 [INFO] Ports for service 'znc-irc' have not been found.
2017/09/26 20:35:53 [INFO] Service 'znc-irc' has not been found.
2017/09/26 20:36:00 [WARNING] Could not get config for ConfigMap: znc-https-lb - configMap is not valid, errors: ["method: Additional property method is not allowed"]
2017/09/26 20:36:00 [INFO] Ports for service 'znc-irc' have not been found.
2017/09/26 20:36:00 [INFO] Service 'znc-irc' has not been found.
E0926 20:36:00.214036       7 runtime.go:66] Observed a panic: "index out of range" (runtime error: index out of range)
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/usr/local/go/src/runtime/panic.go:27
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1027
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:708
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:625
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:613
/build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:566
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/usr/local/go/src/runtime/asm_amd64.s:2086
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 85 [running]:
panic(0x12603a0, 0xc4200180a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x12603a0, 0xc4200180a0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).handleConfigForType(0xc4200ee2d0, 0xc420300d80, 0xc42085a120, 0x7, 0xc42085a0fa, 0x3, 0xc4204fac60, 0xc4209027a0, 0x12, 0xc4208e9b20, ...)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:1027 +0xa25
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).syncVirtualServer(0xc4200ee2d0, 0xc42085a120, 0x7, 0xc42085a0fa, 0x3, 0x0, 0x0)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:708 +0x675
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).processNextVirtualServer(0xc4200ee2d0, 0xc420545600)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:625 +0x147
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).virtualServerWorker(0xc4200ee2d0)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:613 +0x2b
github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).(github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.virtualServerWorker)-fm()
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:566 +0x2a
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42046e4b0)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96 +0x5e
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42046e4b0, 0x3b9aca00, 0x0, 0x1, 0xc42000ca80)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0xad
github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42046e4b0, 0x3b9aca00, 0xc42000ca80)
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
created by github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager.(*Manager).runImpl
        /build/src/github.com/F5Networks/k8s-bigip-ctlr/pkg/appmanager/appManager.go:566 +0x150
````

The following is the updated YAML that was being applied. The major different here being that the 443 port was being added to the Deployment, Service and the second ConfigMap was being created. 

````yaml
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: znc-deployment
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: znc
    spec:
      containers:
      - name: znc
        image: hickey/znc:latest
        ports:
        - name: znc-irc
          containerPort: 6697
          protocol: TCP
        - name: znc-https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: znc-config-volume
          mountPath: /znc-data
      volumes:
      - name: znc-config-volume
        persistentVolumeClaim:
          claimName: znc-config-claim
---
apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  type: NodePort
  ports:
  - name: znc-irc
    port: 6697
    protocol: TCP
    targetPort: 6697
  - name: znc-https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: znc
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: znc-irc-lb
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.3.json"
  data: |-
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "tcp",
          "partition": "kubernetes",
          "virtualAddress": {
            "bindAddr": "10.4.7.32",
            "port": 6697
          }
        },
        "backend": {
          "serviceName": "znc-irc",
          "servicePort": 6697,
          "healthMonitors": [{
            "interval": 30,
            "protocol": "tcp"
          }]
        }
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: znc-https-lb
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.3.json"
  data: |-
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "kubernetes",
          "virtualAddress": {
            "bindAddr": "10.4.7.32",
            "port": 443
          }
        },
        "backend": {
          "serviceName": "znc-https",
          "servicePort": 443,
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "method": "GET"
          }]
        }
      }
    }
````

Admittedly there is a problem with the health check on port 443 that needs to be corrected, but invalid YAML should not take down the k8s-bigip-ctlr container. At the same time errors that cause a panic should be caught and meaningful error messages should be emitted.

**Comment by amudukutore** [comment]
@hickey - what versions of k8s-bigip-ctlr, BIG-IP, and Kubernetes are you using?

**Comment by hickey** [comment]
Kubernetes: 1.7.4
Big IP: 12.0.0 build 0.0.606
k8s-bigip-ctlr: f5networks/k8s-bigip-ctlr:1.1.0

**Comment by f5gary** [comment]
Thank you for reporting this issue @hickey. Yesterday we released v1.2.0 of k8s-bigip-ctlr, and the new release contains some improvements in how the BIG-IP is configured. I believe that the error you experienced will no longer occur with the v1.2.0 release. Please upgrade to the latest release at your earliest convenience and update this issue accordingly.

**Comment by amudukutore** [comment]
@hickey - are you still seeing this issue with v1.2.0 of the k8s-bigip-ctlr? If not, we'd like to close out the issue. Thanks.

**Comment by hickey** [comment]
I have not noticed this issue again, but then I have been focusing on bringing up other ingress controllers that have as many problems. I have had a bunch of configuration issues (mostly from lack of good documentation and having to guess at settings there are) and a lot of spurious errors in the last week or two. I have been keeping my local F5 support person in the loop, but I have gotten very little substantial results. Even after visits from people like Matt Q. and statements made that someone could assist with getting the configurations working there has been virtually no traction. 

So yes, you are welcome to close this issue.  I have no desire to pursue it when I can not get support for the product without pulling a lot of teeth and I am not interested to only setting up ingress controllers for Wordpress sites.

**Comment by sjberman** [comment]
@hickey Here is a link to our Ingress controller documentation: http://clouddocs.f5.com/containers/v1/kubernetes/kctlr-ingress.html, and also a link to the general configuration parameters for the controller: http://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/v1.2/. Let us know if there is missing information that you would like to see in the documentation.
