### ISSUE TITLE
conflict with App Svcs iApp and OpenShift routes

### ISSUE THREAD

**Issue by chen23** [F5Networks/k8s-bigip-ctlr#413]
#### Description
When deploying an App Svcs iApp it triggers an error in the controller.

#### Kubernetes Version
OpenShift Origin 1.5.1

#### Controller Version
1.3.0

#### BIG-IP Version
12.1.1

#### Diagnostic Information
```
2017/10/31 16:22:07 [INFO] [2017-10-31 16:22:07,193 f5_cccl.resource.resource INFO] Updating ApiVirtualServer: /kubernetes/ose-vserver
2017/10/31 16:22:07 [INFO] Exception in thread Thread-1:
2017/10/31 16:22:07 [INFO] Traceback (most recent call last):
2017/10/31 16:22:07 [INFO]   File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2017/10/31 16:22:07 [INFO]     self.run()
2017/10/31 16:22:07 [INFO]   File "/usr/local/lib/python2.7/threading.py", line 754, in run
2017/10/31 16:22:07 [INFO]     self.__target(*self.__args, **self.__kwargs)
2017/10/31 16:22:07 [INFO]   File "/app/python/bigipconfigdriver.py", line 330, in _do_reset
2017/10/31 16:22:07 [INFO]     incomplete += mgr._apply_ltm_config(cfg_ltm)
2017/10/31 16:22:07 [INFO]   File "/app/python/bigipconfigdriver.py", line 105, in _apply_ltm_config
2017/10/31 16:22:07 [INFO]     return self._cccl.apply_config(config)
2017/10/31 16:22:07 [INFO]   File "/app/src/f5-cccl/f5_cccl/api.py", line 74, in apply_config
2017/10/31 16:22:07 [INFO]     return self._service_manager.apply_config(services)
2017/10/31 16:22:07 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 376, in apply_config
2017/10/31 16:22:07 [INFO]     retval = self._service_deployer.deploy(desired_config)
2017/10/31 16:22:07 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 322, in deploy
2017/10/31 16:22:07 [INFO]     self._post_deploy(desired_config)
2017/10/31 16:22:07 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 182, in _post_deploy
2017/10/31 16:22:07 [INFO]     self._bigip.refresh()
2017/10/31 16:22:07 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 144, in refresh
2017/10/31 16:22:07 [INFO]     self._refresh()
2017/10/31 16:22:07 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 277, in _refresh
2017/10/31 16:22:07 [INFO]     if self._policy_status_check(p, virtuals)
2017/10/31 16:22:07 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 193, in _policy_status_check
2017/10/31 16:22:07 [INFO]     v.update()
2017/10/31 16:22:07 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/tm/ltm/virtual.py", line 74, in update
2017/10/31 16:22:07 [INFO]     result = self._update(**kwargs)
2017/10/31 16:22:07 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 582, in _update
2017/10/31 16:22:07 [INFO]     response = session.put(update_uri, json=data_dict, **requests_params)
2017/10/31 16:22:07 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/session.py", line 272, in wrapper
2017/10/31 16:22:07 [INFO]     raise iControlUnexpectedHTTPError(error_message, response=response)
2017/10/31 16:22:07 [INFO] iControlUnexpectedHTTPError: 400 Unexpected Error: Bad Request for uri: https://10.1.20.6:443/mgmt/tm/ltm/virtual/~kubernetes~my-project_demoweb.appsvcs.iapp.vs.app~my-project_demoweb.appsvcs.iapp.vs_vs/
2017/10/31 16:22:07 [INFO] Text: u'{"code":400,"message":"010715bc:3: The application service (/kubernetes/my-project_demoweb.appsvcs.iapp.vs.app/my-project_demoweb.appsvcs.iapp.vs) has strict updates enabled, the object (Virtual Server /kubernetes/my-project_demoweb.appsvcs.iapp.vs.app/my-project_demoweb.appsvcs.iapp.vs_vs) must be updated using an application management interface.","errorStack":[],"apiError":3}'
2017/10/31 16:22:07 [INFO]
```
ConfigMap
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: demoweb.appsvcs.iapp.vs
  namespace: my-project
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.2.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "my-website2",
          "servicePort": 80
        },
        "frontend": {
          "partition": "kubernetes",
          "iapp": "/Common/appsvcs_integration_v2.0.004",
          "iappPoolMemberTable": {
            "name": "pool__Members",
            "columns": [
                {"name": "Index", "value": "0"},
                {"name": "IPAddress", "kind": "IPAddress"},
                {"name": "Port", "kind": "Port"},
                {"name": "ConnectionLimit", "value": "1000"},
                {"name": "Ratio", "value": "1"},
                {"name": "PriorityGroup", "value": "0"},
                {"name": "State", "value": "enabled"}
            ]
          },
          "iappTables": {
            "l7policy__rulesMatch": {
              "columns": ["Group", "Operand", "Negate", "Condition", "Value",
                          "CaseSensitive", "Missing"],
              "rows": [["0", "http-uri/request/path", "no", "starts-with",
                        "/env", "no", "no"],
                       ["default", "", "no", "", "", "no", "no"]]
            },
            "l7policy__rulesAction": {
              "columns": ["Group", "Target", "Parameter"],
              "rows": [["0", "forward/request/reset", "none"],
                       ["default", "forward/request/select/pool", "pool:0"]]
            },
            "pool__Pools": {
              "columns": ["Index", "Name", "Description", "LbMethod",
                          "Monitor", "AdvOptions"],
              "rows": [["0", "", "", "round-robin", "0", "none"]]
            },
            "monitor__Monitors": {
              "columns": ["Index", "Name", "Type", "Options"],
              "rows": [["0", "/Common/tcp", "none", "none"]]
            }
          },
          "iappOptions": {
            "description": "my-website2.appsvcs iApp",
            "trafficGroup": "/Common/traffic-group-2"
          },
          "iappVariables": {
            "iapp__strictUpdates":"enabled",
            "feature__easyL4Firewall":"auto",
            "pool__addr": "10.1.10.103",
            "pool__port": "80",
            "pool__mask": "255.255.255.255",
            "vs__Name": "my-project_demoweb.appsvcs.iapp.vs_vs",
            "vs__ProfileClientProtocol": "/Common/tcp-wan-optimized",
            "vs__ProfileServerProtocol": "/Common/tcp-lan-optimized",
            "vs__ProfileHTTP": "/Common/http",
            "vs__SNATConfig": "automap",
            "iapp__logLevel": "7",
            "iapp__routeDomain": "auto",
            "iapp__mode": "auto",
            "pool__DefaultPoolIndex": "0",
            "l7policy__strategy": "/Common/first-match"
          }
        }
      }
    }
```
Routes
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: 2017-10-31T16:19:46Z
    name: node-blue
    namespace: my-project
    resourceVersion: "764833"
    selfLink: /oapi/v1/namespaces/my-project/routes/node-blue
    uid: 4f7a45bc-be57-11e7-8b78-0a34f875fb12
  spec:
    host: blue.f5demo.com
    to:
      kind: Service
      name: node-blue
      weight: 100
    wildcardPolicy: None
  status:
    ingress: null
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: 2017-10-31T16:19:46Z
    name: node-green
    namespace: my-project
    resourceVersion: "764834"
    selfLink: /oapi/v1/namespaces/my-project/routes/node-green
    uid: 4f7ab113-be57-11e7-8b78-0a34f875fb12
  spec:
    host: green.f5demo.com
    to:
      kind: Service
      name: node-green
      weight: 100
    wildcardPolicy: None
  status:
    ingress: null
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```

**Comment by edarzins** [comment]
This is a CCCL bug. In  _policy_status_check() we need to ignore policies that belong to iApps.

**Comment by edarzins** [comment]
Fixed via https://github.com/f5devcentral/f5-cccl/commit/dd2ef5aa93175e41f64c4f95ba6bc5d714237f44
