### ISSUE TITLE
F5 CTLR reauthenticate

### ISSUE THREAD

**Issue by johscheuer** [F5Networks/k8s-bigip-ctlr#578]
#### Description
(enhancement)

The F5 K8s CTLR should be able to reauthenticate after a fail-over otherwise the F5 K8s CTLR won't be able to configure any new/changed services of the BigIP. After manually restarting the F5 K8s CTLR everything worked fine again.  Our BigIP setup exist out of two BigIP's that are synchronised in an active-passive mode.

There are two possible solutions (from my perspective): 
- Implement reauthentication in side the F5 K8s CTLR
- Add an health check if the F5 K8s CTLR can talk (authenticated) to the BigIP (in a fail-over scenario this would lead to in unsuccessful health check which means that Kubernetes would restart the pod after the restart the F5 CTLR would automatically authenicate at the active BigIP)

This is linked to: https://github.com/F5Networks/k8s-bigip-ctlr/issues/450

#### Kubernetes Version
1.9.3

#### Controller Version
1.4.1

#### BIG-IP Version
-

#### Diagnostic Information
This is the error output after the fail-over:

```bash
2018/02/20 10:32:53 [INFO] Text: u'{"code":401,"message":"X-F5-Auth-Token does not exist.","referer":"10.242.195.4","restOperationId":30929671,"errorStack":["java.lang.SecurityException: X-F5-Auth-Token does not exist.","at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:236)","at com.f5.rest.workers.EvaluatePermissions.access$100(EvaluatePermissions.java:22)","at com.f5.rest.workers.EvaluatePermissions$1.failed(EvaluatePermissions.java:93)","at com.f5.rest.workers.EvaluatePermissions$1.failed(EvaluatePermissions.java:84)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2423)","at com.f5.rest.common.RestCollectionItemsLoadedCompletion.failed(RestCollectionItemsLoadedCompletion.java:103)","at com.f5.rest.common.RestCollectionItemsLoadedCompletion.failed(RestCollectionItemsLoadedCompletion.java:29)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2423)","at com.f5.rest.workers.storage.StorageWorker.onQuery(StorageWorker.java:220)","at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1059)","at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)","at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1348)","at com.f5.rest.common.RestServer.access$000(RestServer.java:45)","at com.f5.rest.common.RestServer$1.run(RestServer.java:309)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:745)\\n"],"kind":":resterrorresponse"}'
2018/02/20 10:32:53 [ERROR] [2018-02-20 10:32:53,342 __main__ ERROR] Error applying config, will try again in 64 seconds
2018/02/20 10:33:57 [ERROR] [2018-02-20 10:33:57,369 __main__ ERROR] Unexpected error
2018/02/20 10:33:57 [INFO] Traceback (most recent call last):
2018/02/20 10:33:57 [INFO]   File "/app/python/bigipconfigdriver.py", line 324, in _do_reset
2018/02/20 10:33:57 [INFO]     incomplete = self._update_cccl(config)
2018/02/20 10:33:57 [INFO]   File "/app/python/bigipconfigdriver.py", line 403, in _update_cccl
2018/02/20 10:33:57 [INFO]     incomplete += mgr._apply_ltm_config(cfg_ltm)
2018/02/20 10:33:57 [INFO]   File "/app/python/bigipconfigdriver.py", line 117, in _apply_ltm_config
2018/02/20 10:33:57 [INFO]     return self._cccl.apply_ltm_config(config)
2018/02/20 10:33:57 [INFO]   File "/app/src/f5-cccl/f5_cccl/api.py", line 83, in apply_ltm_config
2018/02/20 10:33:57 [INFO]     return self._service_manager.apply_ltm_config(services)
2018/02/20 10:33:57 [INFO]   File "/app/src/f5-cccl/f5_cccl/service/manager.py", line 521, in apply_ltm_config
2018/02/20 10:33:57 [INFO]     default_route_domain = self._bigip.get_default_route_domain()
2018/02/20 10:33:57 [INFO]   File "/app/src/f5-cccl/f5_cccl/bigip.py", line 433, in get_default_route_domain
2018/02/20 10:33:57 [INFO]     name=self._partition)
2018/02/20 10:33:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 1054, in load
2018/02/20 10:33:57 [INFO]     return self._load(**kwargs)
2018/02/20 10:33:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5/bigip/resource.py", line 1033, in _load
2018/02/20 10:33:57 [INFO]     response = refresh_session.get(base_uri, **kwargs)
2018/02/20 10:33:57 [INFO]   File "/usr/local/lib/python2.7/site-packages/icontrol/session.py", line 271, in wrapper
2018/02/20 10:33:57 [INFO]     raise iControlUnexpectedHTTPError(error_message, response=response)
2018/02/20 10:33:57 [INFO] iControlUnexpectedHTTPError: 401 Unexpected Error: F5 Authorization Required for uri: https://10.90.34.133:443/mgmt/tm/auth/partition/test
2018/02/20 10:33:57 [INFO] Text: u'{"code":401,"message":"X-F5-Auth-Token does not exist.","referer":"10.242.195.4","restOperationId":30929916,"errorStack":["java.lang.SecurityException: X-F5-Auth-Token does not exist.","at com.f5.rest.workers.EvaluatePermissions.failPermissionValidation(EvaluatePermissions.java:236)","at com.f5.rest.workers.EvaluatePermissions.access$100(EvaluatePermissions.java:22)","at com.f5.rest.workers.EvaluatePermissions$1.failed(EvaluatePermissions.java:93)","at com.f5.rest.workers.EvaluatePermissions$1.failed(EvaluatePermissions.java:84)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2423)","at com.f5.rest.common.RestCollectionItemsLoadedCompletion.failed(RestCollectionItemsLoadedCompletion.java:103)","at com.f5.rest.common.RestCollectionItemsLoadedCompletion.failed(RestCollectionItemsLoadedCompletion.java:29)","at com.f5.rest.common.RestOperation.fail(RestOperation.java:2423)","at com.f5.rest.workers.storage.StorageWorker.onQuery(StorageWorker.java:220)","at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1059)","at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1026)","at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1348)","at com.f5.rest.common.RestServer.access$000(RestServer.java:45)","at com.f5.rest.common.RestServer$1.run(RestServer.java:309)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:745)\\n"],"kind":":resterrorresponse"}'
```

**Comment by russokj** [comment]
The f5-icontrol-rest (v1.3.4) does not internally handle token authentication errors.  A generic iControlUnexpectedHTTPError exception is thrown in this case as is seen in the log above.  Ideally, the package should detect token authentication failures/timeouts and reauthenticate. At a minimum, it should clear it's internal token value so that the next request will reauthenticate.

For HA deployments, we advise one controller per Big-IP.  Our documentation will be updated in the near term to describe this setup more thoroughly.

**Comment by johscheuer** [comment]
@russokj Thanks for the information will close this (since 1.4.2 actually handle the case above)
