### ISSUE TITLE
Controller upgrade to v1.5.0 fails to deploy new BIG-IP configuration

### ISSUE THREAD

**Issue by amudukutore** [F5Networks/k8s-bigip-ctlr#683]
#### Description
When upgrading from a previous version of the controller to v1.5.0, the BIG-IP configurations fail to deploy.

#### OpenShift Version
3.7.1

#### Controller Version
1.5.0

#### BIG-IP Version
<Version of BIG-IP being used>

#### Diagnostic Information
The controller logs show the following messages soon after startup:
```
2018/04/25 14:57:16 [ERROR] [2018-04-25 14:57:16,113 __main__ ERROR] Unexpected error
2018/04/25 14:57:16 [INFO] Traceback (most recent call last):
2018/04/25 14:57:16 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 323, in _do_reset
2018/04/25 14:57:16 [INFO]     incomplete = self._update_cccl(config)
2018/04/25 14:57:16 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 397, in _update_cccl
2018/04/25 14:57:16 [INFO]     incomplete += mgr._apply_ltm_config(cfg_ltm)
2018/04/25 14:57:16 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 117, in _apply_ltm_config
2018/04/25 14:57:16 [INFO]     return self._cccl.apply_ltm_config(config)
2018/04/25 14:57:16 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5_cccl/api.py", line 92, in apply_ltm_config
2018/04/25 14:57:16 [INFO]     self._user_agent)
2018/04/25 14:57:16 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5_cccl/service/manager.py", line 670, in apply_ltm_config
2018/04/25 14:57:16 [INFO]     desired_config, default_route_domain)
2018/04/25 14:57:16 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5_cccl/service/manager.py", line 392, in deploy_ltm
2018/04/25 14:57:16 [INFO]     self._get_resource_tasks(existing_virtuals, desired)[0:4])
2018/04/25 14:57:16 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5_cccl/service/manager.py", line 81, in _get_resource_tasks
2018/04/25 14:57:16 [INFO]     if desired[resource] != managed[resource]
2018/04/25 14:57:16 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5_cccl/resource/resource.py", line 112, in __ne__
2018/04/25 14:57:16 [INFO]     return not self.__eq__(resource)
2018/04/25 14:57:16 [INFO]   File "/usr/local/lib/python2.7/site-packages/f5_cccl/resource/ltm/virtual.py", line 191, in __eq__
2018/04/25 14:57:16 [INFO]     len(self._data[key]) != len(other.data.get(key, None)):
2018/04/25 14:57:16 [INFO] TypeError: object of type 'NoneType' has no len()
2018/04/25 14:57:16 [ERROR] [2018-04-25 14:57:16,117 __main__ ERROR] Error applying config, will try again in 1 seconds
 ```

**Comment by russokj** [comment]
It appears, that the addition of the user-agent metadata is causing a problem.  The metadata is configured as a property list.  If no metadata is defined on the Big-IP when the virtual configuration is retrieved, we will not get a metadata property. This causes a miscompare where we expect to see a list, even if empty:
```
    def __eq__(self, other):
        if not isinstance(other, VirtualServer):
            return False

        for key in self._data:
            # compare list lengths
            if isinstance(self._data[key], list) and \
                    len(self._data[key]) != len(other.data.get(key, None)):
                return False
```
Other resources that may be affected are pools, virtual-addresses, and irule
