### ISSUE TITLE
building error pip no such option: --process-dependency-links

### ISSUE THREAD

**Issue by vincentmli** [F5Networks/k8s-bigip-ctlr#809]
#### Description
<For bug: Describe the bug in detail, observed versus expected behavior, steps to reproduce the issue, and a brief description of your deployment scenario>

I had development environment setup for the controller in Macbook pro, I accidentally removed all the docker images including the python-slim container image, when I run 'make prod' again, I experienced a few errors as below:
<pre>
Installing collected packages: configparser, enum34, pyflakes, mccabe, pycodestyle, flake8, virtualenv
  Running setup.py install for configparser: started
    Running setup.py install for configparser: finished with status 'done'
Successfully installed configparser-3.5.0 enum34-1.1.6 flake8-3.6.0 mccabe-0.6.1 pycodestyle-2.4.0 pyflakes-2.0.0 virtualenv-16.2.0

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

**no such option: --process-dependency-links**
Removing intermediate container c8b688dd4ac7
The command '/bin/sh -c pip install --no-cache-dir --upgrade pip &&     pip install --no-cache-dir setuptools flake8 virtualenv && 	pip install --no-cache-dir --process-dependency-links -r /tmp/requirements.txt && 	pip install --no-cache-dir -r /tmp/requirements.docs.txt && 	go get github.com/wadey/gocovmerge && 	go get golang.org/x/tools/cmd/cover && 	go get github.com/mattn/goveralls && 	go get github.com/onsi/ginkgo/ginkgo && 	go get github.com/onsi/gomega && 	chmod 755 /entrypoint.sh' returned a non-zero code: 2
make: *** [prod-build] Error 2

Successfully installed configparser-3.5.0 enum34-1.1.6 flake8-3.6.0 mccabe-0.6.1 pycodestyle-2.4.0 pyflakes-2.0.0 virtualenv-16.2.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Obtaining f5-ctlr-agent from git+https://github.com/f5devcentral/f5-ctlr-agent.git@671a0defbea9e7def753adb685cbd9230754f131#egg=f5-ctlr-agent (from -r /tmp/requirements.txt (line 1))
  Cloning https://github.com/f5devcentral/f5-ctlr-agent.git (to revision 671a0defbea9e7def753adb685cbd9230754f131) to ./src/f5-ctlr-agent
Collecting f5-cccl (from f5-ctlr-agent->-r /tmp/requirements.txt (line 1))
  **Could not find a version that satisfies the requirement f5-cccl** (from f5-ctlr-agent->-r /tmp/requirements.txt (line 1)) (from versions: )
No matching distribution found for f5-cccl (from f5-ctlr-agent->-r /tmp/requirements.txt (line 1))
Removing intermediate container 07c6a0f23bf2

</pre>

it looks the build process upgraded pip package and the newer pip package does not accept "--process-dependency-links" option, also for some reason f5-cccl is not installed.
 
I am not sure if this is specific to my build environment. I fixed it with below diff

<pre>

diff --git a/build-tools/Dockerfile.debian.builder b/build-tools/Dockerfile.debian.builder
index 1c07d84..7a82126 100755
--- a/build-tools/Dockerfile.debian.builder
+++ b/build-tools/Dockerfile.debian.builder
@@ -61,7 +61,7 @@ COPY requirements.docs.txt /tmp/requirements.docs.txt
 
 RUN pip install --no-cache-dir --upgrade pip && \
     pip install --no-cache-dir setuptools flake8 virtualenv && \
-       pip install --no-cache-dir --process-dependency-links -r /tmp/requirements.txt && \
+       pip install --no-cache-dir -r /tmp/requirements.txt && \
        pip install --no-cache-dir -r /tmp/requirements.docs.txt && \
        go get github.com/wadey/gocovmerge && \
        go get golang.org/x/tools/cmd/cover && \
diff --git a/build-tools/Dockerfile.debian.runtime b/build-tools/Dockerfile.debian.runtime
index 418c8a6..36d3809 100755
--- a/build-tools/Dockerfile.debian.runtime
+++ b/build-tools/Dockerfile.debian.runtime
@@ -13,7 +13,7 @@ COPY requirements.txt /tmp/requirements.txt
 RUN apt-get update && apt-get install -y --no-install-recommends \
         git \
     && pip install --no-cache-dir --upgrade pip \
-    && pip install --no-cache-dir --process-dependency-links -r /tmp/requirements.txt \
+    && pip install --no-cache-dir -r /tmp/requirements.txt \
     && apt-get remove -y git
 
 COPY bigip-virtual-server_v*.json $APPPATH/vendor/src/f5/schemas/

diff --git a/requirements.txt b/requirements.txt
index 8969ed3..25dbf27 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1 +1,2 @@
 -e git+https://github.com/f5devcentral/f5-ctlr-agent.git@671a0defbea9e7def753adb685cbd9230754f131#egg=f5-ctlr-agent
+-e git+https://github.com/f5devcentral/f5-cccl.git@cfaaa7713fddf9fe28400317548d25b104d3b865#egg=f5-cccl

</pre>

#### Kubernetes Version
<Version of Kubernetes being used>

#### Controller Version
<Version of k8s-bigip-ctlr being used>

#### BIG-IP Version
<Version of BIG-IP being used>

#### Diagnostic Information
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137

**Comment by vincentmli** [comment]
also for a fresh ubuntu 18.04.1 installation, I have to come up with below hack to make the build succeed

<pre>

diff --git a/build-tools/Dockerfile.debian.builder b/build-tools/Dockerfile.debian.builder
index 1c07d84..7a82126 100755
--- a/build-tools/Dockerfile.debian.builder
+++ b/build-tools/Dockerfile.debian.builder
@@ -61,7 +61,7 @@ COPY requirements.docs.txt /tmp/requirements.docs.txt
 
 RUN pip install --no-cache-dir --upgrade pip && \
     pip install --no-cache-dir setuptools flake8 virtualenv && \
-       pip install --no-cache-dir --process-dependency-links -r /tmp/requirements.txt && \
+       pip install --no-cache-dir -r /tmp/requirements.txt && \
        pip install --no-cache-dir -r /tmp/requirements.docs.txt && \
        go get github.com/wadey/gocovmerge && \
        go get golang.org/x/tools/cmd/cover && \
diff --git a/build-tools/Dockerfile.debian.runtime b/build-tools/Dockerfile.debian.runtime
index 418c8a6..36d3809 100755
--- a/build-tools/Dockerfile.debian.runtime
+++ b/build-tools/Dockerfile.debian.runtime
@@ -13,7 +13,7 @@ COPY requirements.txt /tmp/requirements.txt
 RUN apt-get update && apt-get install -y --no-install-recommends \
         git \
     && pip install --no-cache-dir --upgrade pip \
-    && pip install --no-cache-dir --process-dependency-links -r /tmp/requirements.txt \
+    && pip install --no-cache-dir -r /tmp/requirements.txt \
     && apt-get remove -y git
 
 COPY bigip-virtual-server_v*.json $APPPATH/vendor/src/f5/schemas/
diff --git a/build-tools/entrypoint.builder.sh b/build-tools/entrypoint.builder.sh
index b7dc782..11e5ed4 100755
--- a/build-tools/entrypoint.builder.sh
+++ b/build-tools/entrypoint.builder.sh
@@ -23,4 +23,4 @@ else
     source scl_source enable python27
 fi
 
-exec $su_binary user "$@"
+exec $su_binary root "$@"
diff --git a/next-version.txt b/next-version.txt
index 27f9cd3..943f9cb 100644
--- a/next-version.txt
+++ b/next-version.txt
@@ -1 +1 @@
-1.8.0
+1.7.1
diff --git a/requirements.txt b/requirements.txt
index 8969ed3..25dbf27 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1 +1,2 @@
 -e git+https://github.com/f5devcentral/f5-ctlr-agent.git@671a0defbea9e7def753adb685cbd9230754f131#egg=f5-ctlr-agent
+-e git+https://github.com/f5devcentral/f5-cccl.git@cfaaa7713fddf9fe28400317548d25b104d3b865#egg=f5-cccl

</pre>

**Comment by vincentmli** [comment]
when I build the CC image with these changes, when run the CC in cluster mode with flannel vxlan, I got error:
<pre>
2019/02/07 03:34:02 [INFO] Starting: Version: 1.7.1, BuildInfo: root-b8bcfc0-dirty-20190206192533
2019/02/07 03:34:02 [INFO] ConfigWriter started: 0xc0003126c0
2019/02/07 03:34:02 [INFO] Started config driver sub-process at pid: 15
2019/02/07 03:34:02 [INFO] NodePoller (0xc000266090) registering new listener: 0x1829650
2019/02/07 03:34:02 [INFO] NodePoller (0xc000266090) registering new listener: 0x18296c0
2019/02/07 03:34:02 [INFO] NodePoller started: (0xc000266090)
2019/02/07 03:34:02 [INFO] Watching ConfigMap resources.
2019/02/07 03:34:02 [INFO] Handling ConfigMap resource events.
2019/02/07 03:34:02 [INFO] Registered BigIP Metrics
2019/02/07 03:34:03 [INFO] Wrote 2 Virtual Server and 0 IApp configs
2019/02/07 03:34:10 [ERROR] [2019-02-07 03:34:10,407 __main__ ERROR] Unexpected error
2019/02/07 03:34:10 [INFO] Traceback (most recent call last):
2019/02/07 03:34:10 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 812, in main
2019/02/07 03:34:10 [INFO]     schema_path=_find_net_schema())
2019/02/07 03:34:10 [INFO]   File "/app/src/f5-ctlr-agent/f5_ctlr_agent/bigipconfigdriver.py", line 762, in _find_net_schema
2019/02/07 03:34:10 [INFO]     log.Error('Could not find CCCL schema: {}'.format(NET_SCHEMA_NAME))
2019/02/07 03:34:10 [INFO] AttributeError: 'Logger' object has no attribute 'Error'
2019/02/07 03:34:10 [CRITICAL] Config driver exited: 1

</pre>

the reason I think this is related because I only made above build-tool diff changes, nothing else. I could not go back to my original pre python pip upgrade since I removed the python-slim container image by mistake

**Comment by vincentmli** [comment]
for now I found a workaround in my macbook pro dev box, with following changes, basically stop running the pip upgrade command 

<pre>

diff -u Dockerfile.debian.builder Dockerfile.debian.builder-nopip-upgrade 
--- Dockerfile.debian.builder	2019-02-07 10:49:47.000000000 -0800
+++ Dockerfile.debian.builder-nopip-upgrade	2019-02-07 10:47:49.000000000 -0800
@@ -59,8 +59,7 @@
 COPY requirements.txt /tmp/requirements.txt
 COPY requirements.docs.txt /tmp/requirements.docs.txt
 
-RUN pip install --no-cache-dir --upgrade pip && \
-    pip install --no-cache-dir setuptools flake8 virtualenv && \
+RUN pip install --no-cache-dir setuptools flake8 virtualenv && \
 	pip install --no-cache-dir --process-dependency-links -r /tmp/requirements.txt && \
 	pip install --no-cache-dir -r /tmp/requirements.docs.txt && \
 	go get github.com/wadey/gocovmerge && \


diff -u Dockerfile.debian.runtime Dockerfile.debian.runtime-nopip-upgrade 
--- Dockerfile.debian.runtime	2019-02-07 10:50:22.000000000 -0800
+++ Dockerfile.debian.runtime-nopip-upgrade	2019-02-07 10:48:08.000000000 -0800
@@ -12,7 +12,6 @@
 
 RUN apt-get update && apt-get install -y --no-install-recommends \
         git \
-    && pip install --no-cache-dir --upgrade pip \
     && pip install --no-cache-dir --process-dependency-links -r /tmp/requirements.txt \
     && apt-get remove -y git
<pre>

does not work on my fresh ubuntu 18.04 install though, it seems the pip is already upgraded and won't accept the --process-dependency-links
